apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: messager-prod

resources:
  - ../../base

patches:
  - path: frontend-replicas-patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: frontend
  - path: bff-replicas-patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: bff
  - path: user-service-replicas-patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: user-service
  - path: message-service-replicas-patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: message-service

images:
  - name: mablinov2704/frontend
    newTag: "latest"
  - name: mablinov2704/bff
    newTag: "latest"
  - name: mablinov2704/user-service
    newTag: "latest"
  - name: mablinov2704/message-service
    newTag: "latest"