# StorageClass для S3 CSI
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: s3-csi
provisioner: ru.yandex.s3.csi
parameters:
  mounter: geesefs
  options: "--memory-limit 1000 --dir-mode 0777 --file-mode 0666"
  bucket: test-for-demo
  csi.storage.k8s.io/provisioner-secret-name: csi-s3-secret
  csi.storage.k8s.io/controller-publish-secret-name: csi-s3-secret
  csi.storage.k8s.io/node-stage-secret-name: csi-s3-secret
  csi.storage.k8s.io/node-publish-secret-name: csi-s3-secret
---
# Secret с доступом к S3 (Cloud.ru)
apiVersion: v1
kind: Secret
metadata:
  name: csi-s3-secret
type: Opaque
stringData:
  accessKeyID: a5e9e272b6d0ed2ae6d6d2f23f1cb060
  secretAccessKey: 04796bb8887b230d3cbab37f73a64b8d
  endpoint: https://s3.cloud.ru
  region: "ru-central-1"