apiVersion: v1
kind: Secret
metadata:
  name: messager-db-secret
  namespace: messager-dev
type: Opaque
stringData:
  POSTGRES_USER: "messager_app"
  POSTGRES_PASSWORD: "V7qjP9sL4uZt3xR2"

  MSG_DB_DSN: "host=postgres user=messager_app password=V7qjP9sL4uZt3xR2 dbname=messages_db sslmode=disable"
  USER_DB_DSN: "host=postgres user=messager_app password=V7qjP9sL4uZt3xR2 dbname=users_db sslmode=disable"

  MSGDBDSN: "host=postgres user=messager_app password=V7qjP9sL4uZt3xR2 dbname=messages_db sslmode=disable"
  USERDBDSN: "host=postgres user=messager_app password=V7qjP9sL4uZt3xR2 dbname=users_db sslmode=disable"