apiVersion: v1
kind: Secret
metadata:
  name: messager-db-secret
type: Opaque
stringData:
  USER_DB_DSN: host=postgres user=messager_app password=V7qjP9sL4uZt3xR2 dbname=postgres sslmode=disable
  MSG_DB_DSN: host=postgres user=messager_app password=V7qjP9sL4uZt3xR2 dbname=postgres sslmode=disable
  USERDBDSN: host=postgres user=messager_app password=V7qjP9sL4uZt3xR2 dbname=postgres sslmode=disable
  MSGDBDSN: host=postgres user=messager_app password=V7qjP9sL4uZt3xR2 dbname=postgres sslmode=disable